/***********************************************************************

             This file has been automatically generated. 
                      Changes will be overwritten!

 **********************************************************************/

#ifndef EGSE_REGISTER_MAP_LIBPARAM_H
#define EGSE_REGISTER_MAP_LIBPARAM_H

#include "param/param.h"

#include "libparam_custom.h"

extern mm_t mm;

PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_Board_ID_addr, Board_ID, PM_SYSINFO);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_FW_Version_addr, FW_Version, PM_READONLY | PM_SYSINFO);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_HW_Version_addr, HW_Version, PM_READONLY | PM_SYSINFO);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_Scratchpad_addr, Scratchpad, PM_CONF | PM_DEBUG);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_Supported_Boards_addr, Supported_Boards, PM_HIDDEN);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_Configured_Boards_addr, Configured_Boards, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_Uptime_addr, Uptime, PM_READONLY | PM_SYSINFO);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_Event_ConfA_addr, Event_ConfA, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_Event_addr, Event, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_ConfPower_addr, ConfPower, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasureVI_V3_addr, MeasureVI_V3, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasurePower_V3_addr, MeasurePower_V3, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasureVI_V5_addr, MeasureVI_V5, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasurePower_V5_addr, MeasurePower_V5, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasureVI_VBat_addr, MeasureVI_VBat, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasurePower_VBat_addr, MeasurePower_VBat, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasureVI_VBatAlt_addr, MeasureVI_VBatAlt, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MeasurePower_VBatAlt_addr, MeasurePower_VBatAlt, PM_READONLY | PM_TELEM);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_I2CConfA_addr, I2CConfA, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_I2CConfB_addr, I2CConfB, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MultiConf0_addr, MultiConf0, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_ConfTempSense_addr, ConfTempSense, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CANConfA_addr, CANConfA, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CANConfB_addr, CANConfB, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_SerialConf_addr, SerialConf, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_PC104Pins_addr, PC104Pins, PM_HIDDEN);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_XTXMultitester_addr, XTXMultitester, PM_HIDDEN);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_RFRelaysConf_addr, RFRelaysConf, PM_CONF);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MultiConf1_Status_addr, MultiConf1_Status, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MultiConf1_Set_addr, MultiConf1_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MultiConf1_Clear_addr, MultiConf1_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_XDCConfig_addr, XDCConfig, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T0_addr, CSBoard_T0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T1_addr, CSBoard_T1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T2_addr, CSBoard_T2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T3_addr, CSBoard_T3, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T4_addr, CSBoard_T4, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T5_addr, CSBoard_T5, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T6_addr, CSBoard_T6, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_T7_addr, CSBoard_T7, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current0I0_addr, CSBoard_Current0I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current0I1_addr, CSBoard_Current0I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current0I2_addr, CSBoard_Current0I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current1I0_addr, CSBoard_Current1I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current1I1_addr, CSBoard_Current1I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current1I2_addr, CSBoard_Current1I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current2I0_addr, CSBoard_Current2I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current2I1_addr, CSBoard_Current2I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current2I2_addr, CSBoard_Current2I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current3I0_addr, CSBoard_Current3I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current3I1_addr, CSBoard_Current3I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current3I2_addr, CSBoard_Current3I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current4I0_addr, CSBoard_Current4I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current4I1_addr, CSBoard_Current4I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current4I2_addr, CSBoard_Current4I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current5I0_addr, CSBoard_Current5I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current5I1_addr, CSBoard_Current5I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current5I2_addr, CSBoard_Current5I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current6I0_addr, CSBoard_Current6I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current6I1_addr, CSBoard_Current6I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current6I2_addr, CSBoard_Current6I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current7I0_addr, CSBoard_Current7I0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current7I1_addr, CSBoard_Current7I1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_CSBoard_Current7I2_addr, CSBoard_Current7I2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_0_addr, TE_Addr_0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_0_Set_addr, TE_Addr_0_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_0_Clear_addr, TE_Addr_0_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_1_addr, TE_Addr_1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_1_Set_addr, TE_Addr_1_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_1_Clear_addr, TE_Addr_1_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_2_addr, TE_Addr_2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_2_Set_addr, TE_Addr_2_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_2_Clear_addr, TE_Addr_2_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_3_addr, TE_Addr_3, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_3_Set_addr, TE_Addr_3_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_TE_Addr_3_Clear_addr, TE_Addr_3_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_0_addr, MTC_Addr_0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_0_Set_addr, MTC_Addr_0_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_0_Clear_addr, MTC_Addr_0_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_1_addr, MTC_Addr_1, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_1_Set_addr, MTC_Addr_1_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_1_Clear_addr, MTC_Addr_1_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_2_addr, MTC_Addr_2, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_2_Set_addr, MTC_Addr_2_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_2_Clear_addr, MTC_Addr_2_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_3_addr, MTC_Addr_3, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_3_Set_addr, MTC_Addr_3_Set, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_MTC_Addr_3_Clear_addr, MTC_Addr_3_Clear, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_RTOS_Status0_addr, RTOS_Status0, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_UtilI2CConfA_addr, UtilI2CConfA, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_UtilI2CStatus_addr, UtilI2CStatus, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_PreviousEndpoint_addr, PreviousEndpoint, PM_READONLY);
PARAM_DEFINE_CC_STATIC_RAM_UINT32(reg_ConfCommsProtocol_addr, ConfCommsProtocol, PM_CONF);

#endif /* EGSE_REGISTER_MAP_LIBPARAM_H */
