# Each test makefile specifies which targets should be mocked.
TEST_SERIAL_MULTIPLEXER_WRAPS := USART_RXBuffer_IsEmpty USART_RXBuffer_GetByte BSP_psGetTelemetryDriver

TEST_SERIAL_MULTIPLEXER_DEFINES := 